
import java_swift
import java_lang

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:30:32 GMT 2016 ///

/// class java.sql.ClientInfoStatus ///

open class ClientInfoStatus: java_lang.Enum {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.sql.ClientInfoStatus", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var ClientInfoStatusJNIClass: jclass?

    /// public static final java.sql.ClientInfoStatus java.sql.ClientInfoStatus.REASON_UNKNOWN

    private static var REASON_UNKNOWN_FieldID: jfieldID?

    open static var REASON_UNKNOWN: ClientInfoStatus! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REASON_UNKNOWN", fieldType: "Ljava/sql/ClientInfoStatus;", fieldCache: &REASON_UNKNOWN_FieldID, className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass )
            return __value != nil ? ClientInfoStatus( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.ClientInfoStatus java.sql.ClientInfoStatus.REASON_UNKNOWN_PROPERTY

    private static var REASON_UNKNOWN_PROPERTY_FieldID: jfieldID?

    open static var REASON_UNKNOWN_PROPERTY: ClientInfoStatus! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REASON_UNKNOWN_PROPERTY", fieldType: "Ljava/sql/ClientInfoStatus;", fieldCache: &REASON_UNKNOWN_PROPERTY_FieldID, className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass )
            return __value != nil ? ClientInfoStatus( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.ClientInfoStatus java.sql.ClientInfoStatus.REASON_VALUE_INVALID

    private static var REASON_VALUE_INVALID_FieldID: jfieldID?

    open static var REASON_VALUE_INVALID: ClientInfoStatus! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REASON_VALUE_INVALID", fieldType: "Ljava/sql/ClientInfoStatus;", fieldCache: &REASON_VALUE_INVALID_FieldID, className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass )
            return __value != nil ? ClientInfoStatus( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.ClientInfoStatus java.sql.ClientInfoStatus.REASON_VALUE_TRUNCATED

    private static var REASON_VALUE_TRUNCATED_FieldID: jfieldID?

    open static var REASON_VALUE_TRUNCATED: ClientInfoStatus! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REASON_VALUE_TRUNCATED", fieldType: "Ljava/sql/ClientInfoStatus;", fieldCache: &REASON_VALUE_TRUNCATED_FieldID, className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass )
            return __value != nil ? ClientInfoStatus( javaObject: __value ) : nil
        }
    }

    /// private static final java.sql.ClientInfoStatus[] java.sql.ClientInfoStatus.$VALUES

    /// private final java.lang.String java.lang.Enum.name

    /// private final int java.lang.Enum.ordinal

    /// private java.sql.ClientInfoStatus(java.lang.String,int)

    /// public static java.sql.ClientInfoStatus[] java.sql.ClientInfoStatus.values()

    private static var values_MethodID_1: jmethodID?

    open class func values() -> [ClientInfoStatus]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass, methodName: "values", methodSig: "()[Ljava/sql/ClientInfoStatus;", methodCache: &values_MethodID_1, args: &__args, locals: &__locals )
        return JNIType.decode( type: [ClientInfoStatus](), from: __return )
    }


    /// public static java.sql.ClientInfoStatus java.sql.ClientInfoStatus.valueOf(java.lang.String)

    private static var valueOf_MethodID_2: jmethodID?

    open class func valueOf( arg0: String? ) -> ClientInfoStatus! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/String;)Ljava/sql/ClientInfoStatus;", methodCache: &valueOf_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? ClientInfoStatus( javaObject: __return ) : nil
    }

    open class func valueOf( _ _arg0: String? ) -> ClientInfoStatus! {
        return valueOf( arg0: _arg0 )
    }

}
