
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.sql.ClientInfoStatus ///

public enum ClientInfoStatus: Int, JNIObjectProtocol, JNIObjectInit {

    case REASON_UNKNOWN, REASON_UNKNOWN_PROPERTY, REASON_VALUE_INVALID, REASON_VALUE_TRUNCATED

    static let enumConstants = JavaClass(loading: "java.sql.ClientInfoStatus")
        .getEnumConstants()!.map { ClientInfoStatusForward( javaObject: $0.javaObject ) }

    public func underlier() -> ClientInfoStatusForward {
        return ClientInfoStatus.enumConstants[self.rawValue]
    }

    public func localJavaObject(_ locals: UnsafeMutablePointer<[jobject]>) -> jobject? {
        return underlier().localJavaObject( locals )
    }

    public init( javaObject: jobject? ) {
        self = ClientInfoStatus( rawValue: JavaEnum( javaObject: javaObject ).ordinal() )!
    }

    /// public static java.sql.ClientInfoStatus java.sql.ClientInfoStatus.valueOf(java.lang.String)

    private static var valueOf_MethodID_1: jmethodID?

    public static func valueOf( name: String? ) -> ClientInfoStatus! {
        return ClientInfoStatusForward.valueOf( name: name )
    }
    public static func valueOf( _ _name: String? ) -> ClientInfoStatus! {
        return valueOf( name: _name )
    }

    /// public static java.sql.ClientInfoStatus[] java.sql.ClientInfoStatus.values()

    private static var values_MethodID_2: jmethodID?

    public static func values() -> [ClientInfoStatus]! {
        return ClientInfoStatusForward.values( )
    }

}


open class ClientInfoStatusForward: JNIObjectForward {

    private static var ClientInfoStatusJNIClass: jclass?

    /// private static final java.sql.ClientInfoStatus[] java.sql.ClientInfoStatus.$VALUES

    /// public static final java.sql.ClientInfoStatus java.sql.ClientInfoStatus.REASON_UNKNOWN

    private static var REASON_UNKNOWN_FieldID: jfieldID?

    public static var REASON_UNKNOWN: ClientInfoStatus! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REASON_UNKNOWN", fieldType: "Ljava/sql/ClientInfoStatus;", fieldCache: &REASON_UNKNOWN_FieldID, className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? ClientInfoStatus( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.ClientInfoStatus java.sql.ClientInfoStatus.REASON_UNKNOWN_PROPERTY

    private static var REASON_UNKNOWN_PROPERTY_FieldID: jfieldID?

    public static var REASON_UNKNOWN_PROPERTY: ClientInfoStatus! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REASON_UNKNOWN_PROPERTY", fieldType: "Ljava/sql/ClientInfoStatus;", fieldCache: &REASON_UNKNOWN_PROPERTY_FieldID, className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? ClientInfoStatus( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.ClientInfoStatus java.sql.ClientInfoStatus.REASON_VALUE_INVALID

    private static var REASON_VALUE_INVALID_FieldID: jfieldID?

    public static var REASON_VALUE_INVALID: ClientInfoStatus! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REASON_VALUE_INVALID", fieldType: "Ljava/sql/ClientInfoStatus;", fieldCache: &REASON_VALUE_INVALID_FieldID, className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? ClientInfoStatus( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.ClientInfoStatus java.sql.ClientInfoStatus.REASON_VALUE_TRUNCATED

    private static var REASON_VALUE_TRUNCATED_FieldID: jfieldID?

    public static var REASON_VALUE_TRUNCATED: ClientInfoStatus! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "REASON_VALUE_TRUNCATED", fieldType: "Ljava/sql/ClientInfoStatus;", fieldCache: &REASON_VALUE_TRUNCATED_FieldID, className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass )
            defer { JNI.DeleteLocalRef( __value ) }
            return __value != nil ? ClientInfoStatus( javaObject: __value ) : nil
        }
    }

    /// public static java.sql.ClientInfoStatus java.sql.ClientInfoStatus.valueOf(java.lang.String)

    private static var valueOf_MethodID_3: jmethodID?

    open class func valueOf( name: String? ) -> ClientInfoStatus! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        __args[0] = JNIType.toJava( value: name, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/String;)Ljava/sql/ClientInfoStatus;", methodCache: &valueOf_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? ClientInfoStatus( javaObject: __return ) : nil
    }

    open class func valueOf( _ _name: String? ) -> ClientInfoStatus! {
        return valueOf( name: _name )
    }

    /// public static java.lang.Enum java.lang.Enum.valueOf(java.lang.Class,java.lang.String)

    private static var valueOf_MethodID_4: jmethodID?

    open class func valueOf( enumType: java_swift.JavaClass?, name: String? ) -> java_swift.JavaEnum! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        __args[0] = JNIType.toJava( value: enumType, locals: &__locals )
        __args[1] = JNIType.toJava( value: name, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Enum;", methodCache: &valueOf_MethodID_4, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_swift.JavaEnum( javaObject: __return ) : nil
    }

    open class func valueOf( _ _enumType: java_swift.JavaClass?, _ _name: String? ) -> java_swift.JavaEnum! {
        return valueOf( enumType: _enumType, name: _name )
    }

    /// public static java.sql.ClientInfoStatus[] java.sql.ClientInfoStatus.values()

    private static var values_MethodID_5: jmethodID?

    open class func values() -> [ClientInfoStatus]! {
        var __locals = [jobject]()
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/sql/ClientInfoStatus", classCache: &ClientInfoStatusJNIClass, methodName: "values", methodSig: "()[Ljava/sql/ClientInfoStatus;", methodCache: &values_MethodID_5, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [ClientInfoStatus].self, from: __return )
    }


    /// public final int java.lang.Enum.compareTo(java.lang.Enum)

    // Skipping method: false true false false false 

    /// public int java.lang.Enum.compareTo(java.lang.Object)

    // Skipping method: false true false false false 

    /// public final boolean java.lang.Enum.equals(java.lang.Object)

    // Skipping method: false true false false false 

    /// public final native java.lang.Class java.lang.Object.getClass()

    // Skipping method: false true false false false 

    /// public final java.lang.Class java.lang.Enum.getDeclaringClass()

    // Skipping method: false true false false false 

    /// public final int java.lang.Enum.hashCode()

    // Skipping method: false true false false false 

    /// public final java.lang.String java.lang.Enum.name()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.notify()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.notifyAll()

    // Skipping method: false true false false false 

    /// public final int java.lang.Enum.ordinal()

    // Skipping method: false true false false false 

    /// public java.lang.String java.lang.Enum.toString()

    // Skipping method: false true false false false 

    /// public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException

    // Skipping method: false true false false false 

    /// public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException

    // Skipping method: false true false false false 

    /// public final void java.lang.Object.wait() throws java.lang.InterruptedException

    // Skipping method: false true false false false 

}

