
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.sql.NClob ///

public protocol NClob: Clob {

}


open class NClobForward: ClobForward, NClob {

    private static var NClobJNIClass: jclass?

}


