
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:30:32 GMT 2016 ///

/// interface java.sql.NClob ///

public protocol NClob: Clob {

}

open class NClobForward: ClobForward, NClob {

    private static var NClobJNIClass: jclass?

}


