
import java_swift
import java_lang

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.sql.RowIdLifetime ///

open class RowIdLifetime: java_lang.Enum {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.sql.RowIdLifetime", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var RowIdLifetimeJNIClass: jclass?

    /// public static final java.sql.RowIdLifetime java.sql.RowIdLifetime.ROWID_UNSUPPORTED

    private static var ROWID_UNSUPPORTED_FieldID: jfieldID?

    open static var ROWID_UNSUPPORTED: RowIdLifetime! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ROWID_UNSUPPORTED", fieldType: "Ljava/sql/RowIdLifetime;", fieldCache: &ROWID_UNSUPPORTED_FieldID, className: "java/sql/RowIdLifetime", classCache: &RowIdLifetimeJNIClass )
            return __value != nil ? RowIdLifetime( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.RowIdLifetime java.sql.RowIdLifetime.ROWID_VALID_OTHER

    private static var ROWID_VALID_OTHER_FieldID: jfieldID?

    open static var ROWID_VALID_OTHER: RowIdLifetime! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ROWID_VALID_OTHER", fieldType: "Ljava/sql/RowIdLifetime;", fieldCache: &ROWID_VALID_OTHER_FieldID, className: "java/sql/RowIdLifetime", classCache: &RowIdLifetimeJNIClass )
            return __value != nil ? RowIdLifetime( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.RowIdLifetime java.sql.RowIdLifetime.ROWID_VALID_SESSION

    private static var ROWID_VALID_SESSION_FieldID: jfieldID?

    open static var ROWID_VALID_SESSION: RowIdLifetime! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ROWID_VALID_SESSION", fieldType: "Ljava/sql/RowIdLifetime;", fieldCache: &ROWID_VALID_SESSION_FieldID, className: "java/sql/RowIdLifetime", classCache: &RowIdLifetimeJNIClass )
            return __value != nil ? RowIdLifetime( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.RowIdLifetime java.sql.RowIdLifetime.ROWID_VALID_TRANSACTION

    private static var ROWID_VALID_TRANSACTION_FieldID: jfieldID?

    open static var ROWID_VALID_TRANSACTION: RowIdLifetime! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ROWID_VALID_TRANSACTION", fieldType: "Ljava/sql/RowIdLifetime;", fieldCache: &ROWID_VALID_TRANSACTION_FieldID, className: "java/sql/RowIdLifetime", classCache: &RowIdLifetimeJNIClass )
            return __value != nil ? RowIdLifetime( javaObject: __value ) : nil
        }
    }

    /// public static final java.sql.RowIdLifetime java.sql.RowIdLifetime.ROWID_VALID_FOREVER

    private static var ROWID_VALID_FOREVER_FieldID: jfieldID?

    open static var ROWID_VALID_FOREVER: RowIdLifetime! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ROWID_VALID_FOREVER", fieldType: "Ljava/sql/RowIdLifetime;", fieldCache: &ROWID_VALID_FOREVER_FieldID, className: "java/sql/RowIdLifetime", classCache: &RowIdLifetimeJNIClass )
            return __value != nil ? RowIdLifetime( javaObject: __value ) : nil
        }
    }

    /// private static final java.sql.RowIdLifetime[] java.sql.RowIdLifetime.$VALUES

    /// private final java.lang.String java.lang.Enum.name

    /// private final int java.lang.Enum.ordinal

    /// private java.sql.RowIdLifetime(java.lang.String,int)

    /// public static java.sql.RowIdLifetime[] java.sql.RowIdLifetime.values()

    private static var values_MethodID_1: jmethodID?

    open class func values() -> [RowIdLifetime]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/sql/RowIdLifetime", classCache: &RowIdLifetimeJNIClass, methodName: "values", methodSig: "()[Ljava/sql/RowIdLifetime;", methodCache: &values_MethodID_1, args: &__args, locals: &__locals )
        return JNIType.toSwift( type: [RowIdLifetime](), from: __return )
    }


    /// public static java.sql.RowIdLifetime java.sql.RowIdLifetime.valueOf(java.lang.String)

    private static var valueOf_MethodID_2: jmethodID?

    open class func valueOf( name: String? ) -> RowIdLifetime! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: name, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/sql/RowIdLifetime", classCache: &RowIdLifetimeJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/String;)Ljava/sql/RowIdLifetime;", methodCache: &valueOf_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? RowIdLifetime( javaObject: __return ) : nil
    }

    open class func valueOf( _ _name: String? ) -> RowIdLifetime! {
        return valueOf( name: _name )
    }

}

